# CURSO: Análisis de funciones con Python

## Sección 8: Numpy

https://numpy.org/devdocs/user/quickstart.html

Listas

In [ ]:
ls1=[1,2,3,4]
ls2=['a','b','c','d']

print(ls1)

Tamaño de una lista

In [ ]:
len(ls1)

Extraer elementos

In [ ]:
print(ls1[0])
print(ls2[3])
print(ls1[-4])

In [ ]:
ls2[1:3]

In [ ]:
ls2[2:3]
ls2[2:]

In [ ]:
ls1[:2]

In [ ]:
ls1[1]=100

print(ls1)

Agregar elemento

In [ ]:
ls1.append(1000)

print(ls1)

Insertar en lista

In [ ]:
ls2.insert(1, "piña")

print(ls2)

In [ ]:
print(lst2 + lst2)

print(lst2*3)

Limpiar lista

In [ ]:
ls2.clear()

print(ls2)

Suma de elementos de la lista 

In [ ]:
import numpy as np
import sympy as sym
from IPython.display import display, Math

In [ ]:
lst=[1,2,3,4,5]

sum(lst)
np.sum(lst)

In [ ]:
np.prod(lst)

In [ ]:
np.cumsum(lst)

Array

In [ ]:
# generate numerator
lst = np.arange(1,6)

print(lst*2)

In [ ]:
xlst = np.linspace(-2, 2, 5)
ylst = np.linspace(-1, 3, 5)

print(len(xlst))
print(xlst[0])
print(xlst)
print(ylst)

ylst*xlst

#print(2*lst)

#print(lst**2)

Matrices

In [121]:
A = np.array( [ [1,2], [3,4] ] )

print(A)


[[1 2]
 [3 4]]


In [125]:
CERO = np.zeros([3,3])

print(CERO)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [127]:
X=np.empty((3,3))

print(X)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [130]:
X[1,1]=1

print(X)

[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]


In [132]:
numrange = range(0,3)
for i in numrange:
    for j in numrange:
        X[i][j] = (-1)**(i+j)
        
print(X)

[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]


Álgebra de vectores

In [138]:
v1 = np.array([-1,2])
v2 = np.array([1,1])

v3a = v1+v2
v3b = np.add(v1,v2)

dp3 = np.dot(v1,v2)

print(dp3)

1
